//! Generate the browser contract from Rust. CI checks the exact checked-in output.
use plasmalab_core::contract::*;
use std::path::PathBuf;
use ts_rs::TS;

fn main() {
    let declarations = [
        Parameters::decl(),
        InitialConditions::decl(),
        Intervention::decl(),
        Experiment::decl(),
        SimulationState::decl(),
        Snapshot::decl(),
        Candidate::decl(),
        Observations::decl(),
        FieldSample::decl(),
        Frame::decl(),
        Preset::decl(),
        ParameterSpec::decl(),
        Catalog::decl(),
        Command::decl(),
        Response::decl(),
    ];
    let mut text = String::from(
        "// Generated by cargo run -p plasmalab-core --example export_types. Do not edit.\n// Scientific wire ownership: crates/plasmalab-core/src/contract.rs.\n\n",
    );
    for declaration in declarations {
        text.push_str("export ");
        text.push_str(&declaration);
        text.push_str("\n\n");
    }
    let text = text
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    let text = format!("{}\n", text.trim_end());
    let path =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../apps/web/src/generated/model.ts");
    if std::env::args().any(|arg| arg == "--check") {
        let existing = std::fs::read_to_string(&path)
            .expect("generated contract is missing; run export_types");
        assert_eq!(existing, text, "generated contract drift; run export_types");
    } else {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, text).unwrap();
    }
}
